name: ACLClouds Auto Renew

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  renew-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Run Renew Script
        env:
          ACL_COOKIES: ${{ secrets.ACL_COOKIES }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python renew.py

      # 将生成的截图上传到 GitHub Actions 页面
      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        if: always() # 无论上面的脚本成功还是失败，都执行上传
        with:
          name: Debug-Screenshots
          path: "*.png" # 上传所有生成的 png 图片
          retention-days: 5 # 截图保留 5 天
